export const INITIAL_STATE = {
  products: [],
  singleProduct: {},
  cartList: JSON.parse(localStorage.getItem("cartList") || "false") || [],
  wishList: JSON.parse(localStorage.getItem("wishList") || "false") || [],
  qtySelected: 1,
  isLoading: false,
  openClose: {
    isNavMenuOpen: false,
    isSearchOpen: false,
    isMenuOpen: false,
    isCartOpen: false,
    isOrderSummaryOpen: false,
    isBillingDetailsOpen: true,
    isPaymentOpen: false,
    isOrderCompleteOpen: false,
    isFilterOpen: false,
    isAlertOpen: false,
  },
  pageTitle: "SHOP - ThriftStarng",
  countryList: [],
  billingDetails: JSON.parse(
    localStorage.getItem("billingDetails") || "false"
  ) || {
    fullName: "",
    email: "",
    phone: "",
    country: "United Kingdom",
    address: "",
    city: "",
    state: "",
    postcode: "",
    createAccount: false,
    gift: false,
    orderNote: "",
    giftFullName: "",
    giftCountry: "United Kingdom",
    giftAddress: "",
    giftCity: "",
    giftState: "",
    giftPostcode: "",
  },
  cartAmounts: {
    itemsAmount: 0,
    shippingFee: 2500,
    tax: 0,
    totalAmount: 0,
  },
  signUpInputs: {
    name: "",
    email: "",
    password: "",
  },
  signInInputs: {
    email: "",
    password: "",
  },
  token: JSON.parse(localStorage.getItem("token") || "false") || "",
  userInfo: JSON.parse(localStorage.getItem("userInfo") || "false") || {},
  isPasswordShown: false,
  pagenation: 10,
  errorMsg: "",
  searchKeyword: "",
  searchResult: [],
  productFilterSort: {
    category: "",
    sort: "",
  },
  alertMessage: "",
};
