export const enum REDUCER_ACTION_TYPES {
  GET_PRODUCTS_LIST,
  GET_SINGLE_PRODUCT,
  ADD_TO_CART,
  DELETE_FROM_CART,
  ADD_TO_WISH,
  DELETE_FROM_WISH,
  QTY_SELECTED,
  LOADING,
  PAGE_TITLE,
  COUNTRY_LIST,
  BILLING_DETAILS,
  SIGNUP_INPUTS,
  SIGNUP,
  SIGNIN_INPUTS,
  GET_USER_INFO,
  CLEAR_PASSWORD_INPUT,
  SHOW_HIDE_PASSWORD,
  CALC_TOTAL,
  OPEN_CLOSE_SEARCH,
  CLOSE_SEARCH,
  OPEN_CLOSE_MENU,
  CLOSE_MENU,
  OPEN_CLOSE_CART,
  CLOSE_CART,
  OPEN_CLOSE_ORDER_SUMMARY,
  CLOSE_ORDER_SUMMARY,
  OPEN_CLOSE_BILLING_DET,
  OPEN_CLOSE_PAYMENT,
  OPEN_CLOSE_ORDER_COMPLETE,
  OPEN_CLOSE_FILTER,
  CLOSE_FILTER,
  OPEN_CLOSE_ALERT,
  CLOSE_ALERT,
  CLEAR_CART,
  PAGENATION,
  ERROR_MSG,
  SEARCH_KEYWORD,
  SEARCH_RESULT,
  CATEGORY,
  SORT,
  CLEAR_FILTER,
  ALERT_MESSAGE
}

export interface Action_A {
  type: REDUCER_ACTION_TYPES;
  field?: any;
  payload?: any; // Don't know what type to put here. I've researched everywhere. Hope to know along the way
}

export type ActionTypes = Action_A;
